"""empty message

Revision ID: 03ffc3bc2be0
Revises: 9cf64c513094
Create Date: 2020-05-31 14:35:22.920943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ffc3bc2be0'
down_revision = '9cf64c513094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('body', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_blog_time_stamp'), 'blog', ['time_stamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_time_stamp'), table_name='blog')
    op.drop_table('blog')
    # ### end Alembic commands ###
