"""empty message

Revision ID: 449a0cd0d153
Revises: 8c766e2284a0
Create Date: 2020-06-19 18:46:39.396171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449a0cd0d153'
down_revision = '8c766e2284a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('tag', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'tag')
    # ### end Alembic commands ###
